import * as Popover from '@radix-ui/react-popover';
import { ChevronRight, SlidersHorizontal, Volume2, X } from 'lucide-react';
import type { FilmGenerationSettings, FilmModel, FilmProject, FilmShot } from './film-project';
import { filmGenerationValues } from './film-references';

export function FilmOutputSettings({ model, project, shot, saved, video, onChange }: { model?: FilmModel; project: FilmProject; shot?: FilmShot; saved: FilmGenerationSettings; video: boolean; onChange: (v: Partial<FilmGenerationSettings>) => void }) {
  const t = model?.template, values = filmGenerationValues(model, project, saved, shot);
  const ratios = t?.aspectRatioOptions || ['9:16', '16:9', '1:1'];
  return <div className="film-output-controls">
    {video && t?.audioSettingOptions?.includes('on') && <label className="film-audio-control"><Volume2 className="film-output-icon" size={20} /><span className="film-output-label"><small className="film-muted">声音</small>{values.audio ? '开启' : '关闭'}</span><input className="film-audio-switch" type="checkbox" role="switch" aria-label="生成音频" checked={values.audio} onChange={e => onChange({ audio: e.target.checked })} /></label>}
    <Popover.Root><Popover.Trigger className="film-output-trigger" aria-label="输出参数"><SlidersHorizontal className="film-output-icon" size={20} /><span className="film-output-label"><small className="film-muted">输出</small><strong className="film-output-summary">{values.ratio} | {values.resolution || '默认'}{video && ` | ${values.duration}秒`}</strong></span><ChevronRight className="film-output-chevron" size={16} /></Popover.Trigger>
      <Popover.Portal><Popover.Content className="film-output-panel" side="right" align="end" sideOffset={12} collisionPadding={14} aria-label="输出参数选择"><header className="film-output-heading"><strong className="film-output-title">输出</strong><Popover.Close className="film-output-close" aria-label="关闭输出参数"><X className="film-output-close-icon" size={17} /></Popover.Close></header>
        <fieldset className="film-output-field"><legend className="film-output-legend">长宽比</legend><div className="film-output-ratios">{ratios.map(r => <button key={r} className={`film-output-ratio ${r === values.ratio ? 'is-active' : ''}`} aria-pressed={r === values.ratio} onClick={() => onChange({ ratio: r })}><span className="film-ratio-symbol" style={{ aspectRatio: r.replace(':', '/'), width: r.includes(':') && Number(r.split(':')[0]) < Number(r.split(':')[1]) ? 10 : 18 }} /><span className="film-ratio-value">{r}</span></button>)}</div></fieldset>
        {!!t?.resolutionOptions?.length && <fieldset className="film-output-field"><legend className="film-output-legend">分辨率</legend><div className="film-output-segments">{t.resolutionOptions.map(r => <button className={r === values.resolution ? 'is-active' : ''} key={r} aria-label={`分辨率 ${r}`} aria-pressed={r === values.resolution} onClick={() => onChange({ resolution: r })}>{r}</button>)}</div></fieldset>}
        {video && <fieldset className="film-output-field"><legend className="film-output-legend">时长 <span className="film-output-current">{values.duration}秒</span></legend>{t?.durationOptions?.length ? <div className="film-output-segments">{t.durationOptions.map(d => <button className={d === values.duration ? 'is-active' : ''} key={d} aria-pressed={d === values.duration} onClick={() => onChange({ duration: d })}>{d}秒</button>)}</div> : <div className="film-output-duration"><input className="film-duration-range" type="range" aria-label="视频时长滑块" min={t?.durationRange?.min || 1} max={t?.durationRange?.max || 30} step={t?.durationRange?.step || 1} value={values.duration} onChange={e => onChange({ duration: Number(e.target.value) })} /><input className="film-duration-input" type="number" aria-label="视频时长" min={t?.durationRange?.min || 1} max={t?.durationRange?.max || 30} step={t?.durationRange?.step || 1} value={values.duration} onChange={e => onChange({ duration: Number(e.target.value) })} /><span className="film-duration-unit">秒</span></div>}</fieldset>}
        {!!t?.outputFormatOptions?.length && <fieldset className="film-output-field"><legend className="film-output-legend">输出格式</legend><div className="film-output-segments">{t.outputFormatOptions.map(f => <button className={f === values.outputFormat ? 'is-active' : ''} key={f} aria-label={`输出格式 ${f}`} aria-pressed={f === values.outputFormat} onClick={() => onChange({ outputFormat: f })}>{f.toUpperCase()}</button>)}</div></fieldset>}
        {!video && !!t?.qualityOptions?.length && <fieldset className="film-output-field"><legend className="film-output-legend">画面质量</legend><div className="film-output-segments">{t.qualityOptions.map(q => <button className={q === values.quality ? 'is-active' : ''} key={q} aria-pressed={q === values.quality} onClick={() => onChange({ quality: q })}>{q}</button>)}</div></fieldset>}
        <p className="film-output-note">仅保存到当前{shot ? '分镜' : '资产'}，批量生成会使用各镜头自己的参数。</p>
      </Popover.Content></Popover.Portal>
    </Popover.Root>
  </div>;
}
