// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const insertAnnouncement = `-- name: InsertAnnouncement :one
INSERT INTO announcements (title, content, created_by)
VALUES ($1, $2, $3)
RETURNING id, title, content, created_at
`

type InsertAnnouncementParams struct {
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type InsertAnnouncementRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (InsertAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement, arg.Title, arg.Content, arg.CreatedBy)
	var i InsertAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT a.id, a.title, a.content, a.created_at,
       COALESCE(u.name, '') AS creator_name
FROM announcements a
LEFT JOIN users u ON u.id = a.created_by
ORDER BY a.created_at DESC
LIMIT $1
`

type ListAnnouncementsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatorName string             `json:"creator_name"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, limit int32) ([]ListAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsRow{}
	for rows.Next() {
		var i ListAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
