// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGenerationLogs = `-- name: CountGenerationLogs :one
SELECT count(*)::int AS total FROM generation_logs
`

func (q *Queries) CountGenerationLogs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countGenerationLogs)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countGenerationsToday = `-- name: CountGenerationsToday :one
SELECT count(*)::int AS total,
       count(*) FILTER (WHERE status = 'success')::int AS success,
       count(*) FILTER (WHERE status = 'error')::int AS errors
FROM generation_logs
WHERE created_at >= CURRENT_DATE
`

type CountGenerationsTodayRow struct {
	Total   int32 `json:"total"`
	Success int32 `json:"success"`
	Errors  int32 `json:"errors"`
}

func (q *Queries) CountGenerationsToday(ctx context.Context) (CountGenerationsTodayRow, error) {
	row := q.db.QueryRow(ctx, countGenerationsToday)
	var i CountGenerationsTodayRow
	err := row.Scan(&i.Total, &i.Success, &i.Errors)
	return i, err
}

const insertGenerationLog = `-- name: InsertGenerationLog :one
INSERT INTO generation_logs (user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost, created_at
`

type InsertGenerationLogParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	NodeID      string         `json:"node_id"`
	ServiceType string         `json:"service_type"`
	Model       string         `json:"model"`
	Prompt      string         `json:"prompt"`
	Status      string         `json:"status"`
	ResultUrl   string         `json:"result_url"`
	ErrorMsg    string         `json:"error_msg"`
	DurationMs  int32          `json:"duration_ms"`
	Cost        pgtype.Numeric `json:"cost"`
}

func (q *Queries) InsertGenerationLog(ctx context.Context, arg InsertGenerationLogParams) (GenerationLog, error) {
	row := q.db.QueryRow(ctx, insertGenerationLog,
		arg.UserID,
		arg.NodeID,
		arg.ServiceType,
		arg.Model,
		arg.Prompt,
		arg.Status,
		arg.ResultUrl,
		arg.ErrorMsg,
		arg.DurationMs,
		arg.Cost,
	)
	var i GenerationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.ServiceType,
		&i.Model,
		&i.Prompt,
		&i.Status,
		&i.ResultUrl,
		&i.ErrorMsg,
		&i.DurationMs,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerationLogs = `-- name: ListGenerationLogs :many
SELECT id, user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost, created_at
FROM generation_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListGenerationLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGenerationLogs(ctx context.Context, arg ListGenerationLogsParams) ([]GenerationLog, error) {
	rows, err := q.db.Query(ctx, listGenerationLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationLog{}
	for rows.Next() {
		var i GenerationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.ServiceType,
			&i.Model,
			&i.Prompt,
			&i.Status,
			&i.ResultUrl,
			&i.ErrorMsg,
			&i.DurationMs,
			&i.Cost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
