// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGenerationLogs = `-- name: CountGenerationLogs :one
SELECT count(*)::int AS total FROM generation_logs
`

func (q *Queries) CountGenerationLogs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countGenerationLogs)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countGenerationLogsWithFilter = `-- name: CountGenerationLogsWithFilter :one
SELECT count(*)::int AS total
FROM generation_logs g
LEFT JOIN users u ON u.id = g.user_id
WHERE ($1::text = '' OR g.status = $1)
  AND ($2::text = '' OR COALESCE(u.name, '') ILIKE '%' || $2 || '%' OR COALESCE(u.email, '') ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR g.model ILIKE '%' || $3 || '%')
`

type CountGenerationLogsWithFilterParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountGenerationLogsWithFilter(ctx context.Context, arg CountGenerationLogsWithFilterParams) (int32, error) {
	row := q.db.QueryRow(ctx, countGenerationLogsWithFilter, arg.Column1, arg.Column2, arg.Column3)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countGenerationsToday = `-- name: CountGenerationsToday :one
SELECT count(*)::int AS total,
       count(*) FILTER (WHERE status = 'success')::int AS success,
       count(*) FILTER (WHERE status = 'error')::int AS errors
FROM generation_logs
WHERE created_at >= CURRENT_DATE
`

type CountGenerationsTodayRow struct {
	Total   int32 `json:"total"`
	Success int32 `json:"success"`
	Errors  int32 `json:"errors"`
}

func (q *Queries) CountGenerationsToday(ctx context.Context) (CountGenerationsTodayRow, error) {
	row := q.db.QueryRow(ctx, countGenerationsToday)
	var i CountGenerationsTodayRow
	err := row.Scan(&i.Total, &i.Success, &i.Errors)
	return i, err
}

const insertGenerationLog = `-- name: InsertGenerationLog :one
INSERT INTO generation_logs (user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost, created_at
`

type InsertGenerationLogParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	NodeID      string      `json:"node_id"`
	ServiceType string      `json:"service_type"`
	Model       string      `json:"model"`
	Prompt      string      `json:"prompt"`
	Status      string      `json:"status"`
	ResultUrl   string      `json:"result_url"`
	ErrorMsg    string      `json:"error_msg"`
	DurationMs  int32       `json:"duration_ms"`
}

func (q *Queries) InsertGenerationLog(ctx context.Context, arg InsertGenerationLogParams) (GenerationLog, error) {
	row := q.db.QueryRow(ctx, insertGenerationLog,
		arg.UserID,
		arg.NodeID,
		arg.ServiceType,
		arg.Model,
		arg.Prompt,
		arg.Status,
		arg.ResultUrl,
		arg.ErrorMsg,
		arg.DurationMs,
	)
	var i GenerationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.ServiceType,
		&i.Model,
		&i.Prompt,
		&i.Status,
		&i.ResultUrl,
		&i.ErrorMsg,
		&i.DurationMs,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerationLogs = `-- name: ListGenerationLogs :many
SELECT id, user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost, created_at
FROM generation_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListGenerationLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGenerationLogs(ctx context.Context, arg ListGenerationLogsParams) ([]GenerationLog, error) {
	rows, err := q.db.Query(ctx, listGenerationLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationLog{}
	for rows.Next() {
		var i GenerationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.ServiceType,
			&i.Model,
			&i.Prompt,
			&i.Status,
			&i.ResultUrl,
			&i.ErrorMsg,
			&i.DurationMs,
			&i.Cost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationLogsWithUser = `-- name: ListGenerationLogsWithUser :many
SELECT g.id, g.user_id, g.node_id, g.service_type, g.model, g.prompt, g.status, g.result_url, g.error_msg, g.duration_ms, g.cost, g.created_at,
       COALESCE(u.email, '') AS user_email,
       COALESCE(u.name, '')  AS user_name
FROM generation_logs g
LEFT JOIN users u ON u.id = g.user_id
WHERE ($1::text = '' OR g.status = $1)
  AND ($2::text = '' OR COALESCE(u.name, '') ILIKE '%' || $2 || '%' OR COALESCE(u.email, '') ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR g.model ILIKE '%' || $3 || '%')
ORDER BY g.created_at DESC
LIMIT $4 OFFSET $5
`

type ListGenerationLogsWithUserParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListGenerationLogsWithUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	NodeID      string             `json:"node_id"`
	ServiceType string             `json:"service_type"`
	Model       string             `json:"model"`
	Prompt      string             `json:"prompt"`
	Status      string             `json:"status"`
	ResultUrl   string             `json:"result_url"`
	ErrorMsg    string             `json:"error_msg"`
	DurationMs  int32              `json:"duration_ms"`
	Cost        pgtype.Numeric     `json:"cost"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserEmail   string             `json:"user_email"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListGenerationLogsWithUser(ctx context.Context, arg ListGenerationLogsWithUserParams) ([]ListGenerationLogsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listGenerationLogsWithUser,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenerationLogsWithUserRow{}
	for rows.Next() {
		var i ListGenerationLogsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.ServiceType,
			&i.Model,
			&i.Prompt,
			&i.Status,
			&i.ResultUrl,
			&i.ErrorMsg,
			&i.DurationMs,
			&i.Cost,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationLogResult = `-- name: UpdateGenerationLogResult :exec
UPDATE generation_logs
SET status = $2,
    result_url = $3,
    error_msg = $4,
    duration_ms = $5,
    cache_hit = $6
WHERE id = $1
`

type UpdateGenerationLogResultParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ResultUrl  string      `json:"result_url"`
	ErrorMsg   string      `json:"error_msg"`
	DurationMs int32       `json:"duration_ms"`
	CacheHit   bool        `json:"cache_hit"`
}

func (q *Queries) UpdateGenerationLogResult(ctx context.Context, arg UpdateGenerationLogResultParams) error {
	_, err := q.db.Exec(ctx, updateGenerationLogResult,
		arg.ID,
		arg.Status,
		arg.ResultUrl,
		arg.ErrorMsg,
		arg.DurationMs,
		arg.CacheHit,
	)
	return err
}

// ─── Hand-written extensions (Stage 2: task recovery polling) ──────────
//
// These are NOT generated by sqlc. They were originally drafted as
// `db/queries/generation_logs.sql` additions, but a full `sqlc generate`
// run conflicts with hand-authored bindings elsewhere in this package
// (notably agent_runs.sql.go). Until that pre-existing mismatch is
// resolved, the additions live here verbatim with the same shape
// sqlc would have produced. Keep in sync with db/queries when sqlc
// regen is reintroduced.

const getGenerationLogByIDForUser = `-- name: GetGenerationLogByIDForUser :one
SELECT id, user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost, created_at
FROM generation_logs
WHERE id = $1 AND user_id = $2
`

type GetGenerationLogByIDForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGenerationLogByIDForUser(ctx context.Context, arg GetGenerationLogByIDForUserParams) (GenerationLog, error) {
	row := q.db.QueryRow(ctx, getGenerationLogByIDForUser, arg.ID, arg.UserID)
	var i GenerationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.ServiceType,
		&i.Model,
		&i.Prompt,
		&i.Status,
		&i.ResultUrl,
		&i.ErrorMsg,
		&i.DurationMs,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestGenerationLogsForUserNodes = `-- name: GetLatestGenerationLogsForUserNodes :many
SELECT DISTINCT ON (node_id)
       id, user_id, node_id, service_type, model, prompt, status, result_url, error_msg, duration_ms, cost, created_at
FROM generation_logs
WHERE user_id = $1
  AND node_id = ANY($2::text[])
ORDER BY node_id, created_at DESC
`

type GetLatestGenerationLogsForUserNodesParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	NodeIDs []string    `json:"node_ids"`
}

func (q *Queries) GetLatestGenerationLogsForUserNodes(ctx context.Context, arg GetLatestGenerationLogsForUserNodesParams) ([]GenerationLog, error) {
	rows, err := q.db.Query(ctx, getLatestGenerationLogsForUserNodes, arg.UserID, arg.NodeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationLog{}
	for rows.Next() {
		var i GenerationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.ServiceType,
			&i.Model,
			&i.Prompt,
			&i.Status,
			&i.ResultUrl,
			&i.ErrorMsg,
			&i.DurationMs,
			&i.Cost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
