// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustCreditBalance = `-- name: AdjustCreditBalance :one
UPDATE credit_accounts
SET current_balance = current_balance + $2,
    updated_at = now()
WHERE user_id = $1
RETURNING id, user_id, daily_quota, current_balance, reset_timezone, last_reset_on, status, updated_at
`

type AdjustCreditBalanceParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	CurrentBalance int32       `json:"current_balance"`
}

func (q *Queries) AdjustCreditBalance(ctx context.Context, arg AdjustCreditBalanceParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, adjustCreditBalance, arg.UserID, arg.CurrentBalance)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyQuota,
		&i.CurrentBalance,
		&i.ResetTimezone,
		&i.LastResetOn,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const adjustCreditQuota = `-- name: AdjustCreditQuota :one
UPDATE credit_accounts
SET daily_quota = $2,
    updated_at = now()
WHERE user_id = $1
RETURNING id, user_id, daily_quota, current_balance, reset_timezone, last_reset_on, status, updated_at
`

type AdjustCreditQuotaParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	DailyQuota int32       `json:"daily_quota"`
}

func (q *Queries) AdjustCreditQuota(ctx context.Context, arg AdjustCreditQuotaParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, adjustCreditQuota, arg.UserID, arg.DailyQuota)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyQuota,
		&i.CurrentBalance,
		&i.ResetTimezone,
		&i.LastResetOn,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const countProviderConfigs = `-- name: CountProviderConfigs :one
SELECT count(*)::int AS total,
       count(*) FILTER (WHERE status = 'enabled')::int AS enabled
FROM provider_configs
`

type CountProviderConfigsRow struct {
	Total   int32 `json:"total"`
	Enabled int32 `json:"enabled"`
}

func (q *Queries) CountProviderConfigs(ctx context.Context) (CountProviderConfigsRow, error) {
	row := q.db.QueryRow(ctx, countProviderConfigs)
	var i CountProviderConfigsRow
	err := row.Scan(&i.Total, &i.Enabled)
	return i, err
}

const countUsers = `-- name: CountUsers :one

SELECT count(*)::int AS total,
       count(*) FILTER (WHERE role = 'admin')::int AS admins,
       count(*) FILTER (WHERE status = 'active')::int AS active
FROM users
`

type CountUsersRow struct {
	Total  int32 `json:"total"`
	Admins int32 `json:"admins"`
	Active int32 `json:"active"`
}

// ─── Admin: Stats ────────────────────────────────────────────────────────────
func (q *Queries) CountUsers(ctx context.Context) (CountUsersRow, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var i CountUsersRow
	err := row.Scan(&i.Total, &i.Admins, &i.Active)
	return i, err
}

const createCreditAccount = `-- name: CreateCreditAccount :one
INSERT INTO credit_accounts (user_id, daily_quota, current_balance)
VALUES ($1, $2, $2)
RETURNING id, user_id, daily_quota, current_balance, reset_timezone, last_reset_on, status, updated_at
`

type CreateCreditAccountParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	DailyQuota int32       `json:"daily_quota"`
}

func (q *Queries) CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, createCreditAccount, arg.UserID, arg.DailyQuota)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyQuota,
		&i.CurrentBalance,
		&i.ResetTimezone,
		&i.LastResetOn,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditLedgerEntry = `-- name: CreateCreditLedgerEntry :exec
INSERT INTO credit_ledger_entries (user_id, account_id, type, amount, balance_after, reason, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCreditLedgerEntryParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	AccountID    pgtype.UUID `json:"account_id"`
	Type         string      `json:"type"`
	Amount       int32       `json:"amount"`
	BalanceAfter int32       `json:"balance_after"`
	Reason       string      `json:"reason"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCreditLedgerEntry(ctx context.Context, arg CreateCreditLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createCreditLedgerEntry,
		arg.UserID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.Reason,
		arg.CreatedBy,
	)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (code_hash, role, initial_daily_quota, max_uses, expires_at, created_by, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code_hash, role, initial_daily_quota, max_uses, used_count, expires_at, created_by, note, created_at, revoked_at
`

type CreateInvitationParams struct {
	CodeHash          string             `json:"code_hash"`
	Role              string             `json:"role"`
	InitialDailyQuota int32              `json:"initial_daily_quota"`
	MaxUses           int32              `json:"max_uses"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Note              string             `json:"note"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.CodeHash,
		arg.Role,
		arg.InitialDailyQuota,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.Note,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.InitialDailyQuota,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createInvitationRedemption = `-- name: CreateInvitationRedemption :exec
INSERT INTO invitation_redemptions (invitation_id, user_id, email)
VALUES ($1, $2, $3)
`

type CreateInvitationRedemptionParams struct {
	InvitationID pgtype.UUID `json:"invitation_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Email        string      `json:"email"`
}

func (q *Queries) CreateInvitationRedemption(ctx context.Context, arg CreateInvitationRedemptionParams) error {
	_, err := q.db.Exec(ctx, createInvitationRedemption, arg.InvitationID, arg.UserID, arg.Email)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, role, status, email_verified_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getCreditAccountByUserID = `-- name: GetCreditAccountByUserID :one
SELECT id, user_id, daily_quota, current_balance, reset_timezone, last_reset_on, status, updated_at
FROM credit_accounts
WHERE user_id = $1
`

func (q *Queries) GetCreditAccountByUserID(ctx context.Context, userID pgtype.UUID) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, getCreditAccountByUserID, userID)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyQuota,
		&i.CurrentBalance,
		&i.ResetTimezone,
		&i.LastResetOn,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByCodeHashForUpdate = `-- name: GetInvitationByCodeHashForUpdate :one
SELECT id, code_hash, role, initial_daily_quota, max_uses, used_count, expires_at, created_by, note, created_at, revoked_at
FROM invitations
WHERE code_hash = $1
FOR UPDATE
`

func (q *Queries) GetInvitationByCodeHashForUpdate(ctx context.Context, codeHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByCodeHashForUpdate, codeHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.InitialDailyQuota,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, status, email_verified_at, last_login_at, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, status, email_verified_at, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInvitationUse = `-- name: IncrementInvitationUse :exec
UPDATE invitations
SET used_count = used_count + 1
WHERE id = $1
`

func (q *Queries) IncrementInvitationUse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementInvitationUse, id)
	return err
}

const listInvitations = `-- name: ListInvitations :many

SELECT i.id, i.code_hash, i.role, i.initial_daily_quota, i.max_uses, i.used_count,
       i.expires_at, i.created_by, i.note, i.created_at, i.revoked_at,
       u.name AS creator_name
FROM invitations i
LEFT JOIN users u ON u.id = i.created_by
ORDER BY i.created_at DESC
`

type ListInvitationsRow struct {
	ID                pgtype.UUID        `json:"id"`
	CodeHash          string             `json:"code_hash"`
	Role              string             `json:"role"`
	InitialDailyQuota int32              `json:"initial_daily_quota"`
	MaxUses           int32              `json:"max_uses"`
	UsedCount         int32              `json:"used_count"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatorName       pgtype.Text        `json:"creator_name"`
}

// ─── Admin: Invitations ──────────────────────────────────────────────────────
func (q *Queries) ListInvitations(ctx context.Context) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Role,
			&i.InitialDailyQuota,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.Note,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many

SELECT u.id, u.email, u.name, u.role, u.status, u.last_login_at, u.created_at,
       COALESCE(ca.daily_quota, 0)::int AS daily_quota,
       COALESCE(ca.current_balance, 0)::int AS current_balance
FROM users u
LEFT JOIN credit_accounts ca ON ca.user_id = u.id
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DailyQuota     int32              `json:"daily_quota"`
	CurrentBalance int32              `json:"current_balance"`
}

// ─── Admin: Users ────────────────────────────────────────────────────────────
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.DailyQuota,
			&i.CurrentBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
RETURNING id, code_hash, role, initial_daily_quota, max_uses, used_count, expires_at, created_by, note, created_at, revoked_at
`

func (q *Queries) RevokeInvitation(ctx context.Context, id pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.InitialDailyQuota,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const sumCreditsConsumedToday = `-- name: SumCreditsConsumedToday :one
SELECT COALESCE(SUM(ABS(amount)), 0)::int AS total
FROM credit_ledger_entries
WHERE type IN ('charge', 'reserve')
  AND created_at >= CURRENT_DATE
`

func (q *Queries) SumCreditsConsumedToday(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, sumCreditsConsumedToday)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, role, status, last_login_at, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

type UpdateUserRoleRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, role, status, last_login_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

type UpdateUserStatusRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i UpdateUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
