// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditAccount = `-- name: CreateCreditAccount :one
INSERT INTO credit_accounts (user_id, daily_quota, current_balance)
VALUES ($1, $2, $2)
RETURNING id, user_id, daily_quota, current_balance, reset_timezone, last_reset_on, status, updated_at
`

type CreateCreditAccountParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	DailyQuota int32       `json:"daily_quota"`
}

func (q *Queries) CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, createCreditAccount, arg.UserID, arg.DailyQuota)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyQuota,
		&i.CurrentBalance,
		&i.ResetTimezone,
		&i.LastResetOn,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditLedgerEntry = `-- name: CreateCreditLedgerEntry :exec
INSERT INTO credit_ledger_entries (user_id, account_id, type, amount, balance_after, reason, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCreditLedgerEntryParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	AccountID    pgtype.UUID `json:"account_id"`
	Type         string      `json:"type"`
	Amount       int32       `json:"amount"`
	BalanceAfter int32       `json:"balance_after"`
	Reason       string      `json:"reason"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCreditLedgerEntry(ctx context.Context, arg CreateCreditLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createCreditLedgerEntry,
		arg.UserID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.Reason,
		arg.CreatedBy,
	)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (code_hash, role, initial_daily_quota, max_uses, expires_at, created_by, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code_hash, role, initial_daily_quota, max_uses, used_count, expires_at, created_by, note, created_at, revoked_at
`

type CreateInvitationParams struct {
	CodeHash          string             `json:"code_hash"`
	Role              string             `json:"role"`
	InitialDailyQuota int32              `json:"initial_daily_quota"`
	MaxUses           int32              `json:"max_uses"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Note              string             `json:"note"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.CodeHash,
		arg.Role,
		arg.InitialDailyQuota,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.Note,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.InitialDailyQuota,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createInvitationRedemption = `-- name: CreateInvitationRedemption :exec
INSERT INTO invitation_redemptions (invitation_id, user_id, email)
VALUES ($1, $2, $3)
`

type CreateInvitationRedemptionParams struct {
	InvitationID pgtype.UUID `json:"invitation_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Email        string      `json:"email"`
}

func (q *Queries) CreateInvitationRedemption(ctx context.Context, arg CreateInvitationRedemptionParams) error {
	_, err := q.db.Exec(ctx, createInvitationRedemption, arg.InvitationID, arg.UserID, arg.Email)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, role, status, email_verified_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditAccountByUserID = `-- name: GetCreditAccountByUserID :one
SELECT id, user_id, daily_quota, current_balance, reset_timezone, last_reset_on, status, updated_at
FROM credit_accounts
WHERE user_id = $1
`

func (q *Queries) GetCreditAccountByUserID(ctx context.Context, userID pgtype.UUID) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, getCreditAccountByUserID, userID)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyQuota,
		&i.CurrentBalance,
		&i.ResetTimezone,
		&i.LastResetOn,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByCodeHashForUpdate = `-- name: GetInvitationByCodeHashForUpdate :one
SELECT id, code_hash, role, initial_daily_quota, max_uses, used_count, expires_at, created_by, note, created_at, revoked_at
FROM invitations
WHERE code_hash = $1
FOR UPDATE
`

func (q *Queries) GetInvitationByCodeHashForUpdate(ctx context.Context, codeHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByCodeHashForUpdate, codeHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.InitialDailyQuota,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, status, email_verified_at, last_login_at, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, status, email_verified_at, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInvitationUse = `-- name: IncrementInvitationUse :exec
UPDATE invitations
SET used_count = used_count + 1
WHERE id = $1
`

func (q *Queries) IncrementInvitationUse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementInvitationUse, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
