// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelayProvider = `-- name: CreateRelayProvider :one
INSERT INTO relay_providers (name, provider_type, base_url, encrypted_api_key)
VALUES ($1, $2, $3, $4)
RETURNING id, name, provider_type, base_url, encrypted_api_key, status, last_sync_at, created_at, updated_at
`

type CreateRelayProviderParams struct {
	Name            string `json:"name"`
	ProviderType    string `json:"provider_type"`
	BaseUrl         string `json:"base_url"`
	EncryptedApiKey string `json:"encrypted_api_key"`
}

func (q *Queries) CreateRelayProvider(ctx context.Context, arg CreateRelayProviderParams) (RelayProvider, error) {
	row := q.db.QueryRow(ctx, createRelayProvider,
		arg.Name,
		arg.ProviderType,
		arg.BaseUrl,
		arg.EncryptedApiKey,
	)
	var i RelayProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.Status,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDefinitionByID = `-- name: GetModelDefinitionByID :one
SELECT id, provider_id, external_model_name, display_name, capability, status,
       parameter_schema, default_parameters, pricing_rule, cost_snapshot, sort_order, created_at, updated_at
FROM model_definitions
WHERE id = $1
`

func (q *Queries) GetModelDefinitionByID(ctx context.Context, id pgtype.UUID) (ModelDefinition, error) {
	row := q.db.QueryRow(ctx, getModelDefinitionByID, id)
	var i ModelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ExternalModelName,
		&i.DisplayName,
		&i.Capability,
		&i.Status,
		&i.ParameterSchema,
		&i.DefaultParameters,
		&i.PricingRule,
		&i.CostSnapshot,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelayProvider = `-- name: GetRelayProvider :one
SELECT id, name, provider_type, base_url, encrypted_api_key, status, last_sync_at, created_at, updated_at
FROM relay_providers
LIMIT 1
`

func (q *Queries) GetRelayProvider(ctx context.Context) (RelayProvider, error) {
	row := q.db.QueryRow(ctx, getRelayProvider)
	var i RelayProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.Status,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModelDefinitionIfNotExists = `-- name: InsertModelDefinitionIfNotExists :one
INSERT INTO model_definitions (provider_id, external_model_name, display_name, capability)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id, external_model_name) DO NOTHING
RETURNING id, provider_id, external_model_name, display_name, capability, status,
          parameter_schema, default_parameters, pricing_rule, cost_snapshot, sort_order, created_at, updated_at
`

type InsertModelDefinitionIfNotExistsParams struct {
	ProviderID        pgtype.UUID `json:"provider_id"`
	ExternalModelName string      `json:"external_model_name"`
	DisplayName       string      `json:"display_name"`
	Capability        string      `json:"capability"`
}

func (q *Queries) InsertModelDefinitionIfNotExists(ctx context.Context, arg InsertModelDefinitionIfNotExistsParams) (ModelDefinition, error) {
	row := q.db.QueryRow(ctx, insertModelDefinitionIfNotExists,
		arg.ProviderID,
		arg.ExternalModelName,
		arg.DisplayName,
		arg.Capability,
	)
	var i ModelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ExternalModelName,
		&i.DisplayName,
		&i.Capability,
		&i.Status,
		&i.ParameterSchema,
		&i.DefaultParameters,
		&i.PricingRule,
		&i.CostSnapshot,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledModelDefinitions = `-- name: ListEnabledModelDefinitions :many
SELECT id, provider_id, external_model_name, display_name, capability, status,
       parameter_schema, default_parameters, pricing_rule, sort_order
FROM model_definitions
WHERE status = 'enabled'
  AND NOT EXISTS (
    SELECT 1
    FROM model_permission_rules denied
    WHERE denied.model_id = model_definitions.id
      AND denied.allowed = false
      AND (
        denied.user_id = $1
        OR denied.role = $2
      )
  )
  AND (
    NOT EXISTS (
      SELECT 1
      FROM model_permission_rules rule
      WHERE rule.model_id = model_definitions.id
    )
    OR EXISTS (
      SELECT 1
      FROM model_permission_rules allowed
      WHERE allowed.model_id = model_definitions.id
        AND allowed.allowed = true
        AND (
          allowed.user_id = $1
          OR allowed.role = $2
        )
    )
  )
ORDER BY sort_order ASC, created_at ASC
`

type ListEnabledModelDefinitionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   pgtype.Text `json:"role"`
}

type ListEnabledModelDefinitionsRow struct {
	ID                pgtype.UUID `json:"id"`
	ProviderID        pgtype.UUID `json:"provider_id"`
	ExternalModelName string      `json:"external_model_name"`
	DisplayName       string      `json:"display_name"`
	Capability        string      `json:"capability"`
	Status            string      `json:"status"`
	ParameterSchema   []byte      `json:"parameter_schema"`
	DefaultParameters []byte      `json:"default_parameters"`
	PricingRule       []byte      `json:"pricing_rule"`
	SortOrder         int32       `json:"sort_order"`
}

func (q *Queries) ListEnabledModelDefinitions(ctx context.Context, arg ListEnabledModelDefinitionsParams) ([]ListEnabledModelDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledModelDefinitions, arg.UserID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledModelDefinitionsRow{}
	for rows.Next() {
		var i ListEnabledModelDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ExternalModelName,
			&i.DisplayName,
			&i.Capability,
			&i.Status,
			&i.ParameterSchema,
			&i.DefaultParameters,
			&i.PricingRule,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelDefinitions = `-- name: ListModelDefinitions :many
SELECT id, provider_id, external_model_name, display_name, capability, status,
       parameter_schema, default_parameters, pricing_rule, cost_snapshot, sort_order, created_at, updated_at
FROM model_definitions
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListModelDefinitions(ctx context.Context) ([]ModelDefinition, error) {
	rows, err := q.db.Query(ctx, listModelDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelDefinition{}
	for rows.Next() {
		var i ModelDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ExternalModelName,
			&i.DisplayName,
			&i.Capability,
			&i.Status,
			&i.ParameterSchema,
			&i.DefaultParameters,
			&i.PricingRule,
			&i.CostSnapshot,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setModelStatus = `-- name: SetModelStatus :one
UPDATE model_definitions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, external_model_name, display_name, capability, status,
          parameter_schema, default_parameters, pricing_rule, cost_snapshot, sort_order, created_at, updated_at
`

type SetModelStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetModelStatus(ctx context.Context, arg SetModelStatusParams) (ModelDefinition, error) {
	row := q.db.QueryRow(ctx, setModelStatus, arg.ID, arg.Status)
	var i ModelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ExternalModelName,
		&i.DisplayName,
		&i.Capability,
		&i.Status,
		&i.ParameterSchema,
		&i.DefaultParameters,
		&i.PricingRule,
		&i.CostSnapshot,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRelayProviderLastSync = `-- name: SetRelayProviderLastSync :exec
UPDATE relay_providers
SET last_sync_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetRelayProviderLastSync(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setRelayProviderLastSync, id)
	return err
}

const updateModelDefinition = `-- name: UpdateModelDefinition :one
UPDATE model_definitions
SET display_name        = $2,
    capability          = $3,
    parameter_schema    = $4,
    default_parameters  = $5,
    pricing_rule        = $6,
    sort_order          = $7,
    updated_at          = now()
WHERE id = $1
RETURNING id, provider_id, external_model_name, display_name, capability, status,
          parameter_schema, default_parameters, pricing_rule, cost_snapshot, sort_order, created_at, updated_at
`

type UpdateModelDefinitionParams struct {
	ID                pgtype.UUID `json:"id"`
	DisplayName       string      `json:"display_name"`
	Capability        string      `json:"capability"`
	ParameterSchema   []byte      `json:"parameter_schema"`
	DefaultParameters []byte      `json:"default_parameters"`
	PricingRule       []byte      `json:"pricing_rule"`
	SortOrder         int32       `json:"sort_order"`
}

func (q *Queries) UpdateModelDefinition(ctx context.Context, arg UpdateModelDefinitionParams) (ModelDefinition, error) {
	row := q.db.QueryRow(ctx, updateModelDefinition,
		arg.ID,
		arg.DisplayName,
		arg.Capability,
		arg.ParameterSchema,
		arg.DefaultParameters,
		arg.PricingRule,
		arg.SortOrder,
	)
	var i ModelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ExternalModelName,
		&i.DisplayName,
		&i.Capability,
		&i.Status,
		&i.ParameterSchema,
		&i.DefaultParameters,
		&i.PricingRule,
		&i.CostSnapshot,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRelayProvider = `-- name: UpdateRelayProvider :one
UPDATE relay_providers
SET base_url            = $2,
    encrypted_api_key   = $3,
    updated_at          = now()
WHERE id = $1
RETURNING id, name, provider_type, base_url, encrypted_api_key, status, last_sync_at, created_at, updated_at
`

type UpdateRelayProviderParams struct {
	ID              pgtype.UUID `json:"id"`
	BaseUrl         string      `json:"base_url"`
	EncryptedApiKey string      `json:"encrypted_api_key"`
}

func (q *Queries) UpdateRelayProvider(ctx context.Context, arg UpdateRelayProviderParams) (RelayProvider, error) {
	row := q.db.QueryRow(ctx, updateRelayProvider, arg.ID, arg.BaseUrl, arg.EncryptedApiKey)
	var i RelayProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.Status,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
