// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CanvasSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Nodes     []byte             `json:"nodes"`
	Edges     []byte             `json:"edges"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CreditAccount struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	DailyQuota     int32              `json:"daily_quota"`
	CurrentBalance int32              `json:"current_balance"`
	ResetTimezone  string             `json:"reset_timezone"`
	LastResetOn    pgtype.Date        `json:"last_reset_on"`
	Status         string             `json:"status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CreditLedgerEntry struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Type            string             `json:"type"`
	Amount          int32              `json:"amount"`
	BalanceAfter    int32              `json:"balance_after"`
	GenerationJobID pgtype.UUID        `json:"generation_job_id"`
	ModelID         pgtype.UUID        `json:"model_id"`
	Reason          string             `json:"reason"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type GenerationLog struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	NodeID      string             `json:"node_id"`
	ServiceType string             `json:"service_type"`
	Model       string             `json:"model"`
	Prompt      string             `json:"prompt"`
	Status      string             `json:"status"`
	ResultUrl   string             `json:"result_url"`
	ErrorMsg    string             `json:"error_msg"`
	DurationMs  int32              `json:"duration_ms"`
	Cost        pgtype.Numeric     `json:"cost"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID                pgtype.UUID        `json:"id"`
	CodeHash          string             `json:"code_hash"`
	Role              string             `json:"role"`
	InitialDailyQuota int32              `json:"initial_daily_quota"`
	MaxUses           int32              `json:"max_uses"`
	UsedCount         int32              `json:"used_count"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type InvitationRedemption struct {
	ID           pgtype.UUID        `json:"id"`
	InvitationID pgtype.UUID        `json:"invitation_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Email        string             `json:"email"`
	RedeemedAt   pgtype.Timestamptz `json:"redeemed_at"`
}

type ModelDefinition struct {
	ID                pgtype.UUID        `json:"id"`
	ProviderID        pgtype.UUID        `json:"provider_id"`
	ExternalModelName string             `json:"external_model_name"`
	DisplayName       string             `json:"display_name"`
	Capability        string             `json:"capability"`
	Status            string             `json:"status"`
	ParameterSchema   []byte             `json:"parameter_schema"`
	DefaultParameters []byte             `json:"default_parameters"`
	PricingRule       []byte             `json:"pricing_rule"`
	CostSnapshot      []byte             `json:"cost_snapshot"`
	SortOrder         int32              `json:"sort_order"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ModelPermissionRule struct {
	ID        pgtype.UUID        `json:"id"`
	ModelID   pgtype.UUID        `json:"model_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      pgtype.Text        `json:"role"`
	Allowed   bool               `json:"allowed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProviderConfig struct {
	ID              pgtype.UUID        `json:"id"`
	ServiceType     string             `json:"service_type"`
	Vendor          string             `json:"vendor"`
	Name            string             `json:"name"`
	ApiSpec         string             `json:"api_spec"`
	BaseUrl         string             `json:"base_url"`
	EncryptedApiKey string             `json:"encrypted_api_key"`
	SubmitEndpoint  string             `json:"submit_endpoint"`
	QueryEndpoint   string             `json:"query_endpoint"`
	ModelList       []string           `json:"model_list"`
	DefaultModel    string             `json:"default_model"`
	Priority        int32              `json:"priority"`
	IsDefault       bool               `json:"is_default"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	// Channel-health fields (migration 011_channel_health). Used by the
	// dynamic routing layer in modelcatalog.application.channel_health to
	// skip cooled-down providers and recover them after the window expires.
	FailureCount         int32              `json:"failure_count"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LastErrorMsg         string             `json:"last_error_msg"`
	LastSuccessAt        pgtype.Timestamptz `json:"last_success_at"`
	CooldownUntil        pgtype.Timestamptz `json:"cooldown_until"`
	ConsecutiveCooldowns int32              `json:"consecutive_cooldowns"`
}

// GenerationAttempt is one upstream HTTP call to a provider on behalf of a
// generation_log entry. Multiple rows per log when fallback fires.
type GenerationAttempt struct {
	ID               pgtype.UUID        `json:"id"`
	GenerationLogID  pgtype.UUID        `json:"generation_log_id"`
	ProviderConfigID pgtype.UUID        `json:"provider_config_id"`
	Vendor           string             `json:"vendor"`
	AttemptNumber    int32              `json:"attempt_number"`
	HttpStatus       pgtype.Int4        `json:"http_status"`
	ErrorMsg         string             `json:"error_msg"`
	DurationMs       pgtype.Int4        `json:"duration_ms"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RelayProvider struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	ProviderType    string             `json:"provider_type"`
	BaseUrl         string             `json:"base_url"`
	EncryptedApiKey string             `json:"encrypted_api_key"`
	Status          string             `json:"status"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
