// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreditAccount struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	DailyQuota     int32              `json:"daily_quota"`
	CurrentBalance int32              `json:"current_balance"`
	ResetTimezone  string             `json:"reset_timezone"`
	LastResetOn    pgtype.Date        `json:"last_reset_on"`
	Status         string             `json:"status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CreditLedgerEntry struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Type            string             `json:"type"`
	Amount          int32              `json:"amount"`
	BalanceAfter    int32              `json:"balance_after"`
	GenerationJobID pgtype.UUID        `json:"generation_job_id"`
	ModelID         pgtype.UUID        `json:"model_id"`
	Reason          string             `json:"reason"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID                pgtype.UUID        `json:"id"`
	CodeHash          string             `json:"code_hash"`
	Role              string             `json:"role"`
	InitialDailyQuota int32              `json:"initial_daily_quota"`
	MaxUses           int32              `json:"max_uses"`
	UsedCount         int32              `json:"used_count"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type InvitationRedemption struct {
	ID           pgtype.UUID        `json:"id"`
	InvitationID pgtype.UUID        `json:"invitation_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Email        string             `json:"email"`
	RedeemedAt   pgtype.Timestamptz `json:"redeemed_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
