// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OwnerID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCanvasSnapshot = `-- name: GetCanvasSnapshot :one
SELECT id, project_id, user_id, nodes, edges, groups, version, created_at
FROM canvas_snapshots
WHERE project_id = $1
`

func (q *Queries) GetCanvasSnapshot(ctx context.Context, projectID pgtype.UUID) (CanvasSnapshot, error) {
	row := q.db.QueryRow(ctx, getCanvasSnapshot, projectID)
	var i CanvasSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Nodes,
		&i.Edges,
		&i.Groups,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, name, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, name, created_at, updated_at
FROM projects
WHERE owner_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE projects
SET name = $2, updated_at = now()
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, name, created_at, updated_at
`

type UpdateProjectNameParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.ID, arg.Name, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCanvasSnapshot = `-- name: UpsertCanvasSnapshot :one
INSERT INTO canvas_snapshots (project_id, user_id, nodes, edges, groups, version)
VALUES ($1, $2, $3, $4, $5, 1)
ON CONFLICT (project_id) DO UPDATE
  SET nodes = EXCLUDED.nodes,
      edges = EXCLUDED.edges,
      groups = EXCLUDED.groups,
      version = canvas_snapshots.version + 1,
      user_id = EXCLUDED.user_id
RETURNING id, project_id, user_id, nodes, edges, groups, version, created_at
`

type UpsertCanvasSnapshotParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Nodes     []byte      `json:"nodes"`
	Edges     []byte      `json:"edges"`
	Groups    []byte      `json:"groups"`
}

func (q *Queries) UpsertCanvasSnapshot(ctx context.Context, arg UpsertCanvasSnapshotParams) (CanvasSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertCanvasSnapshot,
		arg.ProjectID,
		arg.UserID,
		arg.Nodes,
		arg.Edges,
		arg.Groups,
	)
	var i CanvasSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Nodes,
		&i.Edges,
		&i.Groups,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
