// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderConfig = `-- name: CreateProviderConfig :one
INSERT INTO provider_configs (service_type, vendor, name, api_spec, base_url, encrypted_api_key,
       submit_endpoint, query_endpoint, model_list, default_model, priority, is_default, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, service_type, vendor, name, api_spec, base_url, encrypted_api_key,
       submit_endpoint, query_endpoint, model_list, default_model,
       priority, is_default, status, created_at, updated_at
`

type CreateProviderConfigParams struct {
	ServiceType     string   `json:"service_type"`
	Vendor          string   `json:"vendor"`
	Name            string   `json:"name"`
	ApiSpec         string   `json:"api_spec"`
	BaseUrl         string   `json:"base_url"`
	EncryptedApiKey string   `json:"encrypted_api_key"`
	SubmitEndpoint  string   `json:"submit_endpoint"`
	QueryEndpoint   string   `json:"query_endpoint"`
	ModelList       []string `json:"model_list"`
	DefaultModel    string   `json:"default_model"`
	Priority        int32    `json:"priority"`
	IsDefault       bool     `json:"is_default"`
	Status          string   `json:"status"`
}

func (q *Queries) CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) (ProviderConfig, error) {
	row := q.db.QueryRow(ctx, createProviderConfig,
		arg.ServiceType,
		arg.Vendor,
		arg.Name,
		arg.ApiSpec,
		arg.BaseUrl,
		arg.EncryptedApiKey,
		arg.SubmitEndpoint,
		arg.QueryEndpoint,
		arg.ModelList,
		arg.DefaultModel,
		arg.Priority,
		arg.IsDefault,
		arg.Status,
	)
	var i ProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Vendor,
		&i.Name,
		&i.ApiSpec,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.SubmitEndpoint,
		&i.QueryEndpoint,
		&i.ModelList,
		&i.DefaultModel,
		&i.Priority,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :exec
DELETE FROM provider_configs WHERE id = $1
`

func (q *Queries) DeleteProviderConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderConfig, id)
	return err
}

const getProviderConfigByID = `-- name: GetProviderConfigByID :one
SELECT id, service_type, vendor, name, api_spec, base_url, encrypted_api_key,
       submit_endpoint, query_endpoint, model_list, default_model,
       priority, is_default, status, created_at, updated_at
FROM provider_configs
WHERE id = $1
`

func (q *Queries) GetProviderConfigByID(ctx context.Context, id pgtype.UUID) (ProviderConfig, error) {
	row := q.db.QueryRow(ctx, getProviderConfigByID, id)
	var i ProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Vendor,
		&i.Name,
		&i.ApiSpec,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.SubmitEndpoint,
		&i.QueryEndpoint,
		&i.ModelList,
		&i.DefaultModel,
		&i.Priority,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledProviderConfigs = `-- name: ListEnabledProviderConfigs :many
SELECT id, service_type, vendor, name, api_spec, base_url,
       submit_endpoint, query_endpoint, model_list, default_model,
       priority, is_default, status, created_at, updated_at
FROM provider_configs
WHERE status = 'enabled'
ORDER BY service_type, priority ASC
`

type ListEnabledProviderConfigsRow struct {
	ID             pgtype.UUID        `json:"id"`
	ServiceType    string             `json:"service_type"`
	Vendor         string             `json:"vendor"`
	Name           string             `json:"name"`
	ApiSpec        string             `json:"api_spec"`
	BaseUrl        string             `json:"base_url"`
	SubmitEndpoint string             `json:"submit_endpoint"`
	QueryEndpoint  string             `json:"query_endpoint"`
	ModelList      []string           `json:"model_list"`
	DefaultModel   string             `json:"default_model"`
	Priority       int32              `json:"priority"`
	IsDefault      bool               `json:"is_default"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEnabledProviderConfigs(ctx context.Context) ([]ListEnabledProviderConfigsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledProviderConfigsRow{}
	for rows.Next() {
		var i ListEnabledProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceType,
			&i.Vendor,
			&i.Name,
			&i.ApiSpec,
			&i.BaseUrl,
			&i.SubmitEndpoint,
			&i.QueryEndpoint,
			&i.ModelList,
			&i.DefaultModel,
			&i.Priority,
			&i.IsDefault,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
SELECT id, service_type, vendor, name, api_spec, base_url, encrypted_api_key,
       submit_endpoint, query_endpoint, model_list, default_model,
       priority, is_default, status, created_at, updated_at
FROM provider_configs
ORDER BY service_type, priority ASC, created_at ASC
`

func (q *Queries) ListProviderConfigs(ctx context.Context) ([]ProviderConfig, error) {
	rows, err := q.db.Query(ctx, listProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConfig{}
	for rows.Next() {
		var i ProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.ServiceType,
			&i.Vendor,
			&i.Name,
			&i.ApiSpec,
			&i.BaseUrl,
			&i.EncryptedApiKey,
			&i.SubmitEndpoint,
			&i.QueryEndpoint,
			&i.ModelList,
			&i.DefaultModel,
			&i.Priority,
			&i.IsDefault,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderConfig = `-- name: UpdateProviderConfig :one
UPDATE provider_configs
SET service_type     = $2,
    vendor           = $3,
    name             = $4,
    api_spec         = $5,
    base_url         = $6,
    encrypted_api_key = $7,
    submit_endpoint  = $8,
    query_endpoint   = $9,
    model_list       = $10,
    default_model    = $11,
    priority         = $12,
    is_default       = $13,
    status           = $14,
    updated_at       = now()
WHERE id = $1
RETURNING id, service_type, vendor, name, api_spec, base_url, encrypted_api_key,
       submit_endpoint, query_endpoint, model_list, default_model,
       priority, is_default, status, created_at, updated_at
`

type UpdateProviderConfigParams struct {
	ID              pgtype.UUID `json:"id"`
	ServiceType     string      `json:"service_type"`
	Vendor          string      `json:"vendor"`
	Name            string      `json:"name"`
	ApiSpec         string      `json:"api_spec"`
	BaseUrl         string      `json:"base_url"`
	EncryptedApiKey string      `json:"encrypted_api_key"`
	SubmitEndpoint  string      `json:"submit_endpoint"`
	QueryEndpoint   string      `json:"query_endpoint"`
	ModelList       []string    `json:"model_list"`
	DefaultModel    string      `json:"default_model"`
	Priority        int32       `json:"priority"`
	IsDefault       bool        `json:"is_default"`
	Status          string      `json:"status"`
}

func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) (ProviderConfig, error) {
	row := q.db.QueryRow(ctx, updateProviderConfig,
		arg.ID,
		arg.ServiceType,
		arg.Vendor,
		arg.Name,
		arg.ApiSpec,
		arg.BaseUrl,
		arg.EncryptedApiKey,
		arg.SubmitEndpoint,
		arg.QueryEndpoint,
		arg.ModelList,
		arg.DefaultModel,
		arg.Priority,
		arg.IsDefault,
		arg.Status,
	)
	var i ProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Vendor,
		&i.Name,
		&i.ApiSpec,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.SubmitEndpoint,
		&i.QueryEndpoint,
		&i.ModelList,
		&i.DefaultModel,
		&i.Priority,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
