# Download nginx-for-Windows, extract to C:\nginx (or -InstallDir), and write a
# project-specific config that serves dist/ + reverse-proxies /api/ to :8080.
#
# Run as Administrator:
#   powershell -ExecutionPolicy Bypass -File scripts\windows\install-nginx.ps1
#
# Optional params:
#   -InstallDir C:\nginx   (default)
#   -NginxVersion 1.27.3   (default — see http://nginx.org/en/download.html for latest)
#   -Port 80               (frontend listen port; default 80)

param(
  [string]$InstallDir   = 'C:\nginx',
  [string]$NginxVersion = '1.27.3',
  [int]$Port            = 80
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path "$PSScriptRoot\..\..").Path
Set-Location $root

function Log($msg)  { Write-Host "==> $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "!!! $msg" -ForegroundColor Yellow }
function Die($msg)  { Write-Host "xxx $msg" -ForegroundColor Red; exit 1 }

# Admin check
$identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
  Die 'Please re-run this script in an elevated (Administrator) PowerShell.'
}

# 1. Download + extract nginx ────────────────────────────────────────────────
$exe = Join-Path $InstallDir 'nginx.exe'
if (Test-Path $exe) {
  Log "nginx already installed at $InstallDir — skipping download"
} else {
  $zipName = "nginx-$NginxVersion.zip"
  $zipPath = Join-Path $env:TEMP $zipName
  $url     = "http://nginx.org/download/$zipName"

  Log "Downloading $url"
  try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing
  } catch {
    Die "Download failed: $_  (manually download $url, extract to $InstallDir, then re-run with -NginxVersion <ver>)"
  }

  Log "Extracting to $InstallDir"
  $parent = Split-Path $InstallDir -Parent
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  Expand-Archive -Path $zipPath -DestinationPath $parent -Force

  $extracted = Join-Path $parent "nginx-$NginxVersion"
  if (Test-Path $InstallDir) { Remove-Item $InstallDir -Recurse -Force }
  Move-Item $extracted $InstallDir
  Remove-Item $zipPath -Force
  Log "Installed nginx $NginxVersion to $InstallDir"
}

# 2. Write site config ───────────────────────────────────────────────────────
$distPath = ((Resolve-Path "$root\dist").Path) -replace '\\','/'
$logDir   = ((Join-Path $InstallDir 'logs') -replace '\\','/')

$conf = @"
# Auto-generated by scripts\windows\install-nginx.ps1
# Edit if you need extra rules; safe to re-run the install script to regenerate.
worker_processes auto;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    log_format ccy '`$remote_addr - `$remote_user [`$time_local] "`$request" `$status `$body_bytes_sent';
    access_log "$logDir/access.log" ccy;
    error_log  "$logDir/error.log";

    upstream ccy_canvas_backend {
        server 127.0.0.1:8080;
        keepalive 32;
    }

    server {
        listen $Port default_server;
        server_name _;

        root "$distPath";
        index index.html;

        # Static asset caching (Vite emits hashed names).
        location /assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # API reverse-proxy
        location /api/ {
            proxy_pass http://ccy_canvas_backend;
            proxy_http_version 1.1;
            proxy_set_header Host              `$host;
            proxy_set_header X-Real-IP         `$remote_addr;
            proxy_set_header X-Forwarded-For   `$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto `$scheme;
            proxy_set_header Connection "";

            # Video gen can take up to 10 min upstream — match backend cap.
            proxy_connect_timeout 30s;
            proxy_send_timeout    600s;
            proxy_read_timeout    600s;
            client_max_body_size  60m;
            proxy_buffering off;
        }

        # Uploaded files
        location /uploads/ {
            proxy_pass http://ccy_canvas_backend;
            proxy_set_header Host `$host;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        # SPA fallback — every unknown route returns index.html so React Router takes over.
        location / {
            try_files `$uri `$uri/ /index.html;
        }

        # Cache headers for the SPA entry document itself — never cache, so deploys go live instantly.
        location = /index.html {
            add_header Cache-Control "no-store, must-revalidate";
        }
    }
}
"@

$confPath = Join-Path $InstallDir 'conf\nginx.conf'
$enc = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($confPath, $conf, $enc)
Log "Wrote $confPath  (root: $distPath, listen: $Port, upstream: 127.0.0.1:8080)"

# 3. Open firewall ───────────────────────────────────────────────────────────
$ruleName = "CCY Canvas Web ($Port)"
if (-not (Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue)) {
  New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Protocol TCP `
    -LocalPort $Port -Action Allow -Profile Domain,Private | Out-Null
  Log "Added Windows firewall rule '$ruleName' (TCP/$Port, Domain+Private)"
} else {
  Log "Firewall rule '$ruleName' already present"
}

# 4. Test config + start ─────────────────────────────────────────────────────
Push-Location $InstallDir
Log 'Testing nginx config'
& .\nginx.exe -t
if ($LASTEXITCODE -ne 0) { Pop-Location; Die 'nginx -t failed; see error above.' }

# Stop any old instance, then start fresh.
& .\nginx.exe -s stop 2>$null | Out-Null
Start-Sleep -Milliseconds 500
Log 'Starting nginx'
Start-Process -FilePath ".\nginx.exe" -WorkingDirectory $InstallDir -WindowStyle Hidden
Pop-Location

Start-Sleep -Seconds 1
$running = Get-Process -Name 'nginx' -ErrorAction SilentlyContinue
if ($running) {
  Log "nginx running (pids: $((($running | Select-Object -Expand Id) -join ', ')))"
  Write-Host ''
  Write-Host "Open in browser: http://<server-lan-ip>:$Port" -ForegroundColor Cyan
  Write-Host ''
  Write-Host 'Manage:'
  Write-Host "  nginx-reload.ps1     # graceful reload after config edit"
  Write-Host "  nginx-stop.ps1       # stop"
  Write-Host "  nginx-start.ps1      # start"
} else {
  Die 'nginx did not start — check logs in $InstallDir\logs\error.log'
}

# Save InstallDir so the helper scripts can find it.
[System.IO.File]::WriteAllText("$root\run\nginx-install-dir.txt", $InstallDir, $enc)
